<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
  <link rel="stylesheet" href="Lesson9.css">
</head>

<header>
	<img src="pleasure-island-chamber-logo-new.png"</a>
    </header>

<div class="navigation">
<nav class="navibar">
	<ul>
		<li><a href="Pleasure.Island">Home</a></li>
		<li><a href="About.html">About Us</a></li>
		<li><a href="Things.To.Do.html">Things To Do</a></li>
		<li><a href="Member.html">Become A Member</a></li>
	</ul>
	 <a href="javascript:void(0);" class="icon" onclick="myFunction()"></i></a>
</nav>
</div>
